services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    ports:
      - "${PORT_DB}:5432"
    environment:
      POSTGRES_DB: ${NAME_DB}
      POSTGRES_USER: ${USER_DB}
      POSTGRES_PASSWORD: ${PASSWORD_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: